{{- if .Values.frontend.enabled -}}

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.applicationName }}-frontend
  namespace: {{ .Values.applicationName }}-hom 

spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}-frontend
    spec:
      containers:
        - name: {{ .Values.applicationName }}-frontend
          image: nginx
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
              name: http
          resources:
            limits:
              cpu: {{ .Values.frontend.cpuLimit }}
              memory: {{ .Values.frontend.memoryLimit }}
            requests:
              cpu: {{ .Values.frontend.cpuRequest }}
              memory: {{ .Values.frontend.memoryRequest }}

{{- end -}}