{{- if .Values.frontend.imageStream -}}
{{ $name := .Release.Name | trimSuffix "-hom" | trimSuffix "-int" | trimSuffix "-prd"}}
{{- $name := printf "%s-frontend" $name -}}

apiVersion: image.openshift.io/v1
kind: ImageStream

metadata: 
  name: {{ $name }}

spec:
  lookupPolicy:
    local: true

{{- end -}}