{{- if .Values.backend.imageStream -}}
{{ $name := .Release.Name | trimSuffix "-hom" | trimSuffix "-int" | trimSuffix "-prd"}}
{{- if .Values.backend.enabled -}}

apiVersion: image.openshift.io/v1
kind: ImageStream

metadata: 
  name: {{ $name }}

spec:
  lookupPolicy:
    local: true

{{- end -}}