{{- if .Values.frontend.imageStream -}}

apiVersion: image.openshift.io/v1
kind: ImageStream

metadata: 
  name: {{ .Values.applicationName }}-frontend
  namespace: {{ .Values.applicationName }}-hom

spec:
  lookupPolicy:
    local: true

{{- end -}}