{{- if .Values.backend.imageStream -}}

apiVersion: image.openshift.io/v1
kind: ImageStream

metadata: 
  name: {{ .Values.applicationName }}-backend
  namespace: {{ .Values.applicationName }}-hom

spec:
  lookupPolicy:
    local: true

{{- end -}}