{{- if .Values.backend.route -}}
{{ $name := .Release.Name | trimSuffix "-hom" | trimSuffix "-int" | trimSuffix "-prd"}}

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $name}}-backend

spec:
  host: hom-{{ $name}}-backend.apps.ocp.sefaz.pe.gov.br
  to:
    kind: Service
    name: {{ $name}}-backend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

{{- end -}}