{{- if .Values.backend.route -}}

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.applicationName }}-backend
  namespace: {{ .Release.Name }}

spec:
  host: hom-{{ .Values.applicationName }}-backend.apps.ocp.sefaz.pe.gov.br
  to:
    kind: Service
    name: {{ .Values.applicationName }}-backend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

{{- end -}}