{{ if .Values.secrets }}
{{ range $secret := .Values.backend.secrets }}

apiVersion: v1
kind: Secret
metadata:
  name: dbsource
  namespace: {{ .Values.applicationName }}-hom
  labels:
    app: {{ .Values.applicationName }}-backend

{{ end }}
{{ end }}