{{ if .Values.backend.secrets }}
{{ range $secret := .Values.backend.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ .Values.applicationName }}-hom
  labels:
    app: {{ .Values.applicationName }}-backend

---  
{{ end }}
{{ end }}