{{ if .Values.backend.secrets }}
{{ range $secret := .Values.backend.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ .Values.applicationName }}-hom
  labels:
{{ include "argocd.defaultLabels" . | indent 4 }}
    app: {{ .Values.applicationName }}-backend
data:
{{ range $inst := $secret.keys }}

  {{ if $inst.encoded }}
    {{ default "" $inst.name }}: {{ default "" $inst.value | quote }}
  {{ else }}
    {{ default "" $inst.name }}: {{ default "" $inst.value | b64enc | quote }}
  {{ end }}
    
{{ end }}
---
{{ end }}
{{ end }}
