{{ if .Values.secrets }}
{{ range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  labels:
    app: {{ $.Values.applicationName }}-backend
  
data:
{{ range $inst := $secret.keys }}

  {{ if $inst.encoded }}
    {{ default "" $inst.name }}: {{ default "" $inst.value | quote }}
  {{ else }}
    {{ default "" $inst.mame }}: {{ default "" $inst.value | b64enc | quote }}

{{ end }}
---
{{ end }}
{{ end }}