apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secrets.name }}
  namespace: {{ .Values.applicationName }}-hom
  labels:
    app: {{ .Values.applicationName }}-backend
data:
{{ range $inst := $Values.backend.secrets.name.keys }}

  {{ if $inst.encoded }}
    {{ default "" $inst.name }}: {{ default "" $inst.value | quote }}
  {{ else }}
    {{ default "" $inst.name }}: {{ default "" $inst.value | b64enc | quote }}
  {{ end }}
    
{{ end }}