{{ if .Values.secrets }}
{{ range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ .Values.applicationName }}-hom

---
{{ end }}
{{ end }}