{{ if .Values.secrets }}
{{ range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  labels:
    app: {{ .Values.applicationName }}-backend
---
{{ end }}
{{ end }}