{{- if .Values.frontend.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-frontend

spec:
  selector:
    app: {{ .Values.applicationName }}-frontend
  ports:
  - name: http
    port: {{ .Values.frontend.containerPort }}
    targetPort: http

{{- end -}}