{{- if .Values.backend.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-backend

spec:
  selector:
    app: {{ .Values.applicationName }}-backend
  ports:
  - name: http
    port: {{ .Values.backend.containerPort }}
    targetPort: http

{{- end -}}