{{- if .Values.frontend.enabled -}}
{{ $name := .Release.Name | trimSuffix "-hom" | trimSuffix "-int" | trimSuffix "-prd"}}
{{- $name := printf "%s-frontend" $name -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}

spec:
  selector:
    app: {{ $name }}
  ports:
  - name: http
    port: {{ .Values.frontend.containerPort }}
    targetPort: http

{{- end -}}