{{- if .Values.frontend.enabled -}}

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name | trimSuffix "-int" }}-frontend

  annotations:
    image.openshift.io/triggers: |
      [
        {"from":
          {"kind":"ImageStreamTag"
            , "name":"{{ .Release.Name | trimSuffix "-int" }}-frontend:latest"
          }
          , "fieldPath":"spec.template.spec.containers[?(@.name==\"{{ .Release.Name | trimSuffix "-int" }}-frontend\")].image"
        }
      ]


spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name | trimSuffix "-int" }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name | trimSuffix "-int" }}-frontend
    spec:
      containers:
        - name: {{ .Release.Name | trimSuffix "-int" }}-frontend
          image: {{ .Release.Name | trimSuffix "-int" }}-frontend:latest
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
              name: http
          resources:
            limits:
              cpu: {{ .Values.frontend.cpuLimit }}
              memory: {{ .Values.frontend.memoryLimit }}
            requests:
              cpu: {{ .Values.frontend.cpuRequest }}
              memory: {{ .Values.frontend.memoryRequest }}

            livenessProbe:
              httpGet:
                path: /{{ .Release.Name | trimSuffix "-int" }}/
                port: 8080
              initialDelaySeconds: 3
              periodSeconds: 3
            readinessProbe:
              httpGet:
                path: /{{ .Release.Name | trimSuffix "-int" }}/
                port: 8080
              initialDelaySeconds: 3
              periodSeconds: 3

{{- end -}}