{{ $name := .Release.Name | trimSuffix "-hom" | trimSuffix "-int" | trimSuffix "-prd"}}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: developer

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: G_{{ $name | upper }}