{{- if .Values.backend.imageStream -}}

apiVersion: image.openshift.io/v1
kind: ImageStream

metadata: 
  name: {{ .Release.Name | trimSuffix "-int" }}-backend


spec:
  lookupPolicy:
    local: true

{{- end -}}