{{- if .Values.frontend.imageStream -}}

apiVersion: image.openshift.io/v1
kind: ImageStream

metadata: 
  name: {{ .Release.Name | trimSuffix "-int" }}-frontend


spec:
  lookupPolicy:
    local: true

{{- end -}}