{{- if .Values.backend.imageStream -}}
{{ $name := .Release.Name | trimSuffix "-hom" | trimSuffix "-int" | trimSuffix "-prd"}}

apiVersion: image.openshift.io/v1
kind: ImageStream

metadata: 
  name: {{ $name }}-backend


spec:
  lookupPolicy:
    local: true

{{- end -}}