{{- if .Values.frontend.route -}}

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-frontend

spec:
  host: env-{{ .Release.Name }}-frontend.apps.ocp.sefaz.pe.gov.br
  to:
    kind: Service
    name: {{ .Release.Name }}-frontend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

{{- end -}}