{{- if .Values.frontend.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | trimSuffix "-int" }}-frontend


spec:
  selector:
    app: {{ .Release.Name | trimSuffix "-int" }}-frontend
  ports:
  - name: http
    port: {{ .Values.frontend.containerPort }}
    targetPort: http

{{- end -}}