{{- if .Values.backend.enabled -}}
{{ $name := .Release.Name | trimSuffix "-hom" | trimSuffix "-int" | trimSuffix "-prd"}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name}}-backend

spec:
  selector:
    app: {{ $name}}-backend
  ports:
  - name: http
    port: {{ .Values.backend.containerPort }}
    targetPort: http

{{- end -}}