{{- if .Values.backend.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | trimSuffix "-int"}}-backend

spec:
  selector:
    app: {{ .Release.Name | trimSuffix "-int"}}-backend
  ports:
  - name: http
    port: {{ .Values.backend.containerPort }}
    targetPort: http

{{- end -}}