{{- if .Values.backend.enabled -}}

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-backend

spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: {{ .Release.Name }}-backend
          image: nginx
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
              protocol: TCP
              name: http
          resources:
            limits:
              cpu: {{ .Values.backend.cpuLimit }}
              memory: {{ .Values.backend.memoryLimit }}
            requests:
              cpu: {{ .Values.backend.cpuRequest }}
              memory: {{ .Values.backend.memoryRequest }}
          
          env: 
            {{- toYaml .Values.backend.env | nindent 12 }}


{{- end -}}