apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.applicationName}}-prd
  namespace: cicd
spec:
  project: {{ .Values.applicationName}}-prd
  syncPolicy:
    automated: {}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.applicationName}}-prd
  source:
    path: prd
    repoURL: {{ .Values.spec.source.repoURL }}