apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: template-app-gitops-hom
  namespace: openshift-gitops
spec:
  project: app
  syncPolicy:
    automated: {}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: app-hom
  source:
    path: hom
    repoURL: {{ .Values.spec.source.repoURL }}