apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: template-app-gitops-prd
  namespace: openshift-gitops
spec:
  project: app
  syncPolicy:
    automated: {}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: app-prd
  source:
    path: prd
    repoURL: {{ .Values.spec.source.repoURL }}