applicationName: templateapps

backend:
  enabled: true
  replicas: 1
  containerPort: 8080
  cpuLimit: 600m
  cpuRequest: 300m
  memoryLimit: 512Mi
  memoryRequest: 384Mi
  route: true
  imageStream: true
  
  
  
  env:
    - name: env
      value: >-
        TZ=America/Recife


  livenessProbe:
    initialDelaySeconds: 105
    httpGet:
      path: /actuator/health/liveness
      port: http

  readinessProbe:
    initialDelaySeconds: 105
    httpGet:
      path: /actuator/health/readiness
      port: http

frontend:
  enabled: true
  replicas: 1
  containerPort: 8080
  cpuLimit: 10m
  cpuRequest: 10m
  memoryLimit: 32Mi
  memoryRequest: 32Mi
  route: true
  imageStream: true  


secrets:
  - name: dbsource
    keys:
      - name: DB_APP_URL
        value: "jdbc:exemplo"
      - name: DB_APP_USER
        value: "exemplo"
      - name: DB_APP_PASS
        value: "exemplo"