{{- if .Values.backend.enabled -}}

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.applicationName }}-backend

  annotations:
    image.openshift.io/triggers: |
      [
        {"from":
          {"kind":"ImageStreamTag"
            , "name":"{{ .Values.applicationName }}-backend:stable"
          }
          , "fieldPath":"spec.template.spec.containers[?(@.name==\"{{ .Values.applicationName }}-backend\")].image"
        }
      ]


spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}-backend
    spec:
      containers:
        - name: {{ .Values.applicationName }}-backend
          image: {{ .Values.applicationName }}-backend:stable
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
              protocol: TCP
              name: http
          resources:
            limits:
              cpu: {{ .Values.backend.cpuLimit }}
              memory: {{ .Values.backend.memoryLimit }}
            requests:
              cpu: {{ .Values.backend.cpuRequest }}
              memory: {{ .Values.backend.memoryRequest }}
          
          env: 
            {{- toYaml .Values.backend.env | nindent 12 }}

          {{ if .Values.secrets }}
          {{ range $secret := .Values.secrets }}
          envFrom:
            secretGenerator:
              - name: {{ $secret.name }}
          {{ end }}
          {{ end }}


          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12}}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12}}

{{- end -}}