{{- if .Values.backend.route -}}
{{ $name := .Release.Name | trimSuffix "-hom" | trimSuffix "-int" | trimSuffix "-prd"}}
{{- $name := printf "%s-backend" $name -}}

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $name }}


spec:
  host: prd-{{ $name }}.apps.ocp.sefaz.pe.gov.br
  to:
    kind: Service
    name: {{ $name }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

{{- end -}}