{{- if .Values.frontend.enabled -}}
{{ $name := .Release.Name | trimSuffix "-hom" | trimSuffix "-int" | trimSuffix "-prd"}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-frontend


spec:
  selector:
    app: {{ $name }}-frontend
  ports:
  - name: http
    port: {{ .Values.frontend.containerPort }}
    targetPort: http

{{- end -}}